name: Flask Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t flask-docker-app ./app

      - name: Run Docker Compose
        run: docker compose -f Dockercompose.yaml up -d

      - name: Test the app
        run: |
          sleep 15
          curl -s http://localhost:5000
      
      - name: Log in to Docker Hub 
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: santi2401/flask-docker-app:latest